# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

APO <- function(X, lambda, p, c) {
    .Call('_APO1_APO', PACKAGE = 'APO1', X, lambda, p, c)
}

